### ISSUE TITLE
URLs contain newline characters

### ISSUE THREAD

**Issue by anonrig** [Kikobeats/top-sites#56]
Recent changes in this package caused our dataset to fail. Particularly, the rootDomains contain invalid characters.

```json
[
	{
		"rank": 1,
		"rootDomain": "\n                      youtube.com\n                  ",
		"linkingRootDomains": 100,
		"domainAuthority": 0
	},
]
```

Ref: https://github.com/ada-url/url-dataset/issues/3

cc @lemire

**Comment by Kikobeats** [comment]
Thanks for notifying me; It should be fixed in the latest version.

Keep making ada fast! 🙂
