### ISSUE TITLE
HTTPError: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by eugeny-dementev** [Kikobeats/top-sites#62]
Trying to install another package that has dependency on the current one but the whole installation failing cause `postinstall` script for `top-sites` cannot access hardcoded website `https://moz.com/`

**Comment by Kikobeats** [comment]
It seems it's back to normal 🙂

**Comment by eugeny-dementev** [comment]
It depends on availability of `https://moz.com`
I have no access in my place of living to that website and the fact that it requesting it crashes whole `npm install`
